### ISSUE TITLE
Contact point to ask for some info

### ISSUE THREAD

**Issue by tuxerrante** [ghumman/lfce#3]
Hi,
thanks for the great work!

I'm trying to extend it with a fork, are you interested in merging or should I go on my way? :)

Also, could you PM me to talk shortly about how was you experience? Maybe I should extend more some other topic?
For example in LFS211 course there were no slides on Docker, Linux recovery process etc.. and very poor info on Squid, or how to configure an Apache web server.

Best regards

**Comment by ghumman** [comment]
I'll really appreciate your contribution and will love to merge it. The experience is that I couldn't pass the exam in 2 tries as I don't do networking in my day to day job. I agree that some topics aren't covered in the course but they still show up in the exam. 

I'll be looking forward for your PR. 
Thanks.
